version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: task_traker_user
      POSTGRES_PASSWORD: arqwgzfd%dhssdv
      POSTGRES_DB: task_traker
    ports:
      - 5440:5432

  elasticsearch:
    image: elasticsearch:6.8.6
    container_name: elastic_task_traker_01
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "data01:/usr/share/elasticsearch/data"
      - "./var/tmp:/tmp"

volumes:
  data01:
    driver: local
